server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://0.0.0.0:3306/demo_user?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  shardingsphere:
    sharding:
      default-database-strategy:
      tables:

#      discovery:
#        cluster-name: HZ
mybatis:
  type-aliases-package: cn.cloud.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url:  # eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka
pattern:
  name: 本地环境local